name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: java -jar ./artifacts/app-replan-delivery.jar &
      - name: Wait for server to start
        run: |
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:9999/actuator/health; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 2
          done
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
